### ISSUE TITLE
Laravel 8 compatiblity

### ISSUE THREAD

**Issue by zihadt** [ferdousulhaque/laravel-otp-validate#1]
I would request the dev to update the relevant package version in composer.json for laravel 8 compablity. thanks

**Comment by ferdousulhaque** [comment]
Thank you for the feedback, adding it soon.

**Comment by awwal1999** [comment]
I get this error when I try to install it in Laravel 8

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires ferdous/laravel-otp-validate ^1.1 -> satisfiable by ferdous/laravel-otp-validate[v1.1.0].
    - ferdous/laravel-otp-validate v1.1.0 requires illuminate/support ^7.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev] but it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by ferdousulhaque** [comment]
Fix has been added for Laravel 8 in latest version. Thank you for all your feedbacks. With the remarks, closing this issue.
