### ISSUE TITLE
laravel 5.6.*

### ISSUE THREAD

**Issue by grimm04** [ferdousulhaque/laravel-otp-validate#2]
Problem 1
    - Installation request for ferdous/laravel-otp-validate ^1.1 -> satisfiable by ferdous/laravel-otp-validate[v1.1.0].
    - Conclusion: remove laravel/framework v5.6.40
    - Conclusion: don't install laravel/framework v5.6.40
    - ferdous/laravel-otp-validate v1.1.0 requires illuminate/container ^7.0 -> satisfiable by illuminate/container[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.28.4, v7.29.0, v7.29.1, v7.29.2, v7.29.3, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, 
v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/container v7.0.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.3|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.4|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.5|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.6|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.7|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.0.8|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.1.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.1.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.1.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.1.3|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.10.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.10.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.10.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.10.3|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.11.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.12.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.13.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.14.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.14.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.15.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.16.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.16.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.17.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.17.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.17.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.18.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.19.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.19.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.2.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.2.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.2.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.20.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.21.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.22.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.22.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.22.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.22.3|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.22.4|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.23.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.23.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.23.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.24.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.25.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.26.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.26.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.27.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.28.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.28.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.28.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.28.3|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.28.4|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.29.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.29.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.29.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.29.3|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.3.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.4.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.5.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.5.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.5.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.6.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.6.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.6.2|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.7.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.7.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.8.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.9.0|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.9.1|don't install laravel/framework v5.6.40
    - don't install illuminate/container v7.9.2|don't install laravel/framework v5.6.40
    - Installation request for laravel/framework (locked at v5.6.40, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.40].

**Comment by ferdousulhaque** [comment]
Thank you for the feedback, will check on the issue. However, Laravel 5.6 is a bit older version for this package and for few basic packages it will not allow to install.

**Comment by ferdousulhaque** [comment]
@grimm04 In Laravel 5.6 by default carbon is added with version 1.26.* which is not compatible with this package. Hence, only way is to perform a minor upgrade to Laravel ^5.8.0 and Carbon version to ^2.0.0. Just run the below command first:

`./vendor/bin/upgrade-carbon`

It will start Carbon package upgrade, in the process it will ask for Laravel version minor upgrade, give the consent and then try to install package from composer. It will definitely work then. Let me know, if you are facing any difficulties.

    Do you want us to try the following upgrade:
       - nesbot/carbon: ^2.0.0
       - laravel/framework: ^5.8.0
    [Y/N] Y
