### ISSUE TITLE
Error installing in Laravel 8

### ISSUE THREAD

**Issue by Zaheer-Khawaja** [ferdousulhaque/laravel-otp-validate#3]
First of all; thank you for sharing.
I was trying to install otp-validate in Laravel 8.  Got this message :
I am using MariaDB

composer require ferdous/laravel-otp-validate
Using version ^1.2 for ferdous/laravel-otp-validate
./composer.json has been updated
Running composer update ferdous/laravel-otp-validate
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking ferdous/laravel-otp-validate (v1.2.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading ferdous/laravel-otp-validate (v1.2.0)
  - Installing ferdous/laravel-otp-validate (v1.2.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: aimeos/aimeos-laravel
Discovered Package: facade/ignition
Discovered Package: ferdous/laravel-otp-validate
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: jenssegers/agent
Discovered Package: laravel/fortify
Discovered Package: laravel/jetstream
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: livewire/livewire
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
83 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan migrate
Migrating: 2020_05_21_100000_create_teams_table
Migrated:  2020_05_21_100000_create_teams_table (598.81ms)
Migrating: 2020_05_21_200000_create_team_user_table
Migrated:  2020_05_21_200000_create_team_user_table (376.90ms)
Migrating: 2020_07_12_000000_create_otps_table

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` bigint unsigned not null auto_increment primary key, `client_req_id` varchar(255) not null, `number` varchar(255) null, `email` varchar(255) null, `type` varchar(255) not null, `otp` varchar(255) not null, `uuid` varchar(255) not null, `retry` tinyint not null, `status` enum('new', 'used', 'expired') not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at E:\ZAH\Laravel\moudhah\vendor\laravel\framework\src\Illuminate\Database\Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

  1   E:\ZAH\Laravel\moudhah\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18
      Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")

  2   E:\ZAH\Laravel\moudhah\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:83
      Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
Script @php artisan migrate handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by ferdousulhaque** [comment]
@Zaheer-Khawaja From the error what I understand that, the required Environment variables are not set properly. Please add the following entry to your .env file and it should work. Thank you for pointing, I am updating the README with this entry.

OTP_TABLE_NAME=otps

**Comment by ferdousulhaque** [comment]
With the above fix it should be resolved. So closing the issue.
