### ISSUE TITLE
Root composer.json requires phpseclib/phpseclib ~2.0 but the package is fixed to 3.0.10 (lock file version)

### ISSUE THREAD

**Issue by MustafaTaj** [ferdousulhaque/laravel-otp-validate#5]
so am trying to install the library to my script but am facing this error

    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - Root composer.json requires phpseclib/phpseclib ~2.0, found phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev] but the package is fixed to 3.0.10 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

    Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

    Installation failed, reverting ./composer.json and ./composer.lock to their original content. 

my script is strict to use phpseclib/phpseclib ~2.0

any idea on how to fix it ?

**Comment by ferdousulhaque** [comment]
Not able to regenerate the issue. Can you please help or still are you facing the issue, please let me know.
