### ISSUE TITLE
[Suggestion] Change mailable from blade view to markdown

### ISSUE THREAD

**Issue by JawadR1** [ferdousulhaque/laravel-otp-validate#6]
The current view for email is a simple blade view but Laravel offers an optional markdown view as well.

The advantages of using markdown view over simple blade view are:
- You can write the email in markdown syntax (duh)
- You can use prebuilt [mail components](https://laravel.com/docs/9.x/mail#markdown-mailables) provided by Laravel

It's just one function update and I don't see any disadvantages to using it.

Love to hear your thoughts about this.

**Comment by ferdousulhaque** [comment]
Thanks, let me check it out.

**Comment by alex-ng-wesoft** [comment]
FWIW, I have a local change I'm willing to upstream that allows the class of the mailable to be specified.
Anyone that wants Markdown can create a custom mailable class, while people who want to stick with the default views can just accept the default.

This also makes it much easier for users of the library to customise their e-mails without making changes to this library.
Thoughts?

**Comment by JawadR1** [comment]
Yeah, I think allowing users to specify their own mailable class is the better way.

**Comment by ferdousulhaque** [comment]
@alex-ng-wesoft can you give a pull request to me to review.

**Comment by ihemantkumar** [comment]
@ferdousulhaque Any update on this ticket?
