### ISSUE TITLE
AWS SNS code requires a PHP version newer than the minimum in composer.json

### ISSUE THREAD

**Issue by alex-ng-wesoft** [ferdousulhaque/laravel-otp-validate#9]
# Issue
Currently the library's [composer.json file](https://github.com/ferdousulhaque/laravel-otp-validate/blob/29c7241ca19042bd56085ca1de31cfca700b84e3/composer.json#L37-L38) claims that this library supports PHP v7.1.8 and up.
A quick skim of the code base suggests this is mostly true, but there is a notable exception in [SNSTransportService.php](https://github.com/ferdousulhaque/laravel-otp-validate/blob/29c7241ca19042bd56085ca1de31cfca700b84e3/src/Services/SNSTransportService.php#L28-L29) where type properties are used, which is something [only available in PHP 7.4 or above](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.typed-properties).

Here are some quick commands to prove this:
```
$ docker run -it php:7.3.33-cli-alpine3.14 php -r 'class Foo {public string $bar;}'
> Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in Command line code on line 1
```

```
$ docker run -it php:7.4.29-cli-alpine3.15 php -r 'class Foo {public string $bar;}'
> <No output>
```

As such, the composer.json PHP requirement is technically wrong.

# Potential fixes
1. Update the composer.json file to require PHP 7.4 or above.
2. Update the SNS code to properly support PHP 7.1, 7.2, and 7.3.
3. Document somewhere that SNS support requires PHP 7.4.

Considering even PHP 7.3 is (officially, at least) EOL since December of 2021 I strongly recommend option 1, but the other options are reasonable as well.

**Comment by ferdousulhaque** [comment]
@alex-ng-wesoft Well explained, thanks. Actually I have plans to fix the PHP version 7.4 and above, also to support PHP 8.0 and above same time. Thanks for the suggestion.
